name: codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Generate Coverage Report
      run: go test ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
