name: Go
on:
  - push
  - pull_request
jobs:
  build:
    runs-on:
      - ubuntu-latest
      - freebsd-latest
    steps:
      - name: Set up Go
        uses: actions/checkout@v3 actions/setup-go@v3
        with:
          go-version: "1.19"
        run: go version
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
